import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'material-symbols/rounded.css';
import "./globals.css";
import ThemeProvider from "./providers/theme/theme-provider";
import Navbar from "@/components/navbar/navbar.component";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />

          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
